### PR TITLE
ProtonMail tuto

### PR DESCRIPTION
**Pull request by LoicPandul**
New tutorial on how to set up and use a ProtonMail inbox. The tutorial is part of SCU101 in the practical section.

### CODE REVIEW

**Comment by LoicPandul** [comment]
The PR includes the update of the SCU101 practical section to add the link to the tutorial and remove the paragraph that warned the tutorial was not yet available in their language. However, for Vietnamese, the practical section is missing in SCU101. Should we add it? Thank you.

**Comment by Asi0Flammeus** [comment]
Thanks for this tutorial!

Regarding the missing part with the Vietnamese version, could you point me to it and I will add the missing part and we will then put the tutorial link.

**Comment by LoicPandul** [comment]
On the website : https://planb.network/en/courses/scu101/afc9ab5d-7664-5a9b-ab50-225ac9ba8f7c
On the repo : https://github.com/PlanB-Network/bitcoin-educational-content/blob/dev/courses/scu101/en.md#setting-up-a-mailbox

**Comment by LoicPandul** [comment]
chapterId for the link in the Vietnamese version.
afc9ab5d-7664-5a9b-ab50-225ac9ba8f7c

**Comment by Asi0Flammeus** [comment]
thanks for noticing! I have fixed and added this missing part

**Pull request merged**
