### PR TITLE
Add Btcpayserver course

### PR DESCRIPTION
**Pull request by melontwist**

### CODE REVIEW

**Comment by Asi0Flammeus** [comment]
Hi @melontwist! 

Thanks for this course proposal! 
How do you know [PlanB Network plateform](https://planb.network/)? 
It would be cool to have a whole course on BTCPayServer!
Would you be available to talk about that on a call? Like this, we could work in hand to effectively publish it :-)

**Comment by NicolasDorier** [comment]
hey @Asi0Flammeus I already discussed this with Rogzy. We basically have written a BTCPay book in Figma format right now.
We are converting it in markdown so people can easily contribute and translate.

We'd like this course to be part of PlanB network in an attempt to teach local communities about BTCPay Server.

**Comment by Asi0Flammeus** [comment]
Hi Nicolas! 
Although that is so cool to convert it in .md format, if we want this course on PlanB Network it has to possess a header as such (it's an example): 

```
---
name: BTC303
goal: install btcpayserver for your business
objectives:
  - understand what btcpayserver is
  - self-host and configure btcpayserver
  - use btcpayserver in your daily business
---
``` 

If you need any help, don't hesitate to ping me!

**Comment by NicolasDorier** [comment]
@Asi0Flammeus thanks for the head up, we will add header, there is still a lot to put into md, it's still a draft, @melontwist should be done in April. We'll then all review it after this.

**Comment by Asi0Flammeus** [comment]
Thank you for this extensive course! 

I will review it in the following days. 
Most of my modification will concerned the format of the markdown file. 

My objective is to make it appealing on the PlanB Network website, so I will not change the content part but mostly act on the headings structure.

Once done I'll let you know

**Comment by NicolasDorier** [comment]
@Asi0Flammeus do you have a plan on how to move forward?

**Comment by Asi0Flammeus** [comment]
@NicolasDorier actually yes! 

Couple weeks ago, when I first went through the whole course file, I realised that the initial course's structure ressembles more to a "ready-to-teach" course for a serie of  in-person lectures than an online course. 

Considering this, I'm planning to do two things: 
1. Use this initial material, to create the first `ready-to-teach` folder in course folder which goal would be to provide documents like yours to help people teach this course in their local community. To help me on this, it would be ideal if you send me the corresponding pdf file from which the `md` file was inspired by. 
2. In the following weeks, put someone on reformating the `md` file to mold it as an online course that can be followed autonomously online. 

In any case, I'll keep you informed of the progress

**Comment by Asi0Flammeus** [comment]
The formatting has been completed, I can now merge the new course! :tada: 
It will be now published on the testnet website, I will check one more time about the formatting and potentially do some adjustements. Then it would be published on the mainnet website. 

Thanks again for your contribution! 
BTW if you can provide me more info about the second author of this course called Bas in order to create their professor subfolder. Otherwise only Alekos would be cited as teacher.

**Pull request merged**
