### PR TITLE
proofreading phi201 - vi

### PR DESCRIPTION
**Pull request by Henry-Da0**

### CODE REVIEW

**Comment by Henry-Da0** [comment]
Hi @MariJJhodl , could you have a look please. Thank you.

**Comment by MariJJhodl** [comment]
@Henry-Da0 I saw you made different changes here: can you give some feedback on the original English version? Was it clear?

**Comment by Henry-Da0** [comment]
> @Henry-Da0 I saw you made different changes here: can you give some feedback on the original English version? Was it clear?

I think we need a professional english proofreader to proofread English version. I made change base on the French version.

**Comment by MariJJhodl** [comment]
@Asi0Flammeus from what you indicated in out internal file, this PR was merged. Can you double check and merge it?

**Pull request merged**
