### PR TITLE
[COURSES] Update all courses durations

### PR DESCRIPTION
**Pull request by LoicPandul**
Update all `hours:` keys in the `course.yml` files for all courses based on the new calculation method for durations. I haven't processed the courses that only have videos.

As you'll see, our calculation method produces results that are far, far below the original estimations (e.g., BTC101: 3 hours with the script vs. 15 hours originally). If needed, I can quickly redo the calculations since I now have the script. The calculation method is easy to adjust if necessary. Feel free to tell me.

### CODE REVIEW

**Review by Asi0Flammeus — CHANGES_REQUESTED** [review]
I think that with your current formulae, the evaluation is underestimated.
Could you provide the formulae used, so we can decide which parameter to tweek.

**Comment by LoicPandul** [comment]
Formulae: 

`Hours = (total words * 0.25 + nbr images * 30) * Difficulty Factor / 3600`

0.25 : 4 words per seconde
30" per image

Difficulty Factors:
  - beginner : 1
  - intermediate : 1.5
  - advanced : 2
  - wizard : 2.5

The result is rounded up to the next whole number. @Asi0Flammeus

**Comment by LoicPandul** [comment]
New formulae:

`Hours = (total words * 0.75 + nbr images * 30 + nbr tuto * 600) * Difficulty Factor / 3600`

I added 10 extra minutes per tutorial mentioned in the course (30 minutes was producing crazy results for some courses, it was too much imo). I also modified the number of seconds per word to 0.75. What do you think of theses results?

Python:

```python
def calculate_hours(words, images, tutorial_links, difficulty):
    base_time_seconds = words * 0.75 + images * 30
    tutorial_time_seconds = tutorial_links * 600
    total_time_seconds = (base_time_seconds + tutorial_time_seconds) * difficulty
    return total_time_seconds / 3600
```

**Comment by LoicPandul** [comment]
Script in PR #1085

**Review by Asi0Flammeus — APPROVED** [review]
Seems to me good a better educated guess for hours! Good job!

**Pull request merged**
