### PR TITLE
initial tuto for b-cert verification

### PR DESCRIPTION
**Pull request by midimarcus**
First version of tutorial.

### CODE REVIEW

**Comment by Asi0Flammeus** [comment]
@midimarcus The cover file is missing in the assets folder
could you add one?

**Comment by midimarcus** [comment]
@Asi0Flammeus, cover and logo added.

**Comment by trigger-xyz** [comment]
Should we copy the english version for all languages, until we have proper translation ?

**Comment by midimarcus** [comment]
I think is a good idea. In case of a missing language what is the standard fallback?

**Comment by Asi0Flammeus** [comment]
All translation has been added. 
And for now in the app, there is no fallback so if there is no translation, the content is not available.

**Pull request merged**
