### PR TITLE
[RESOURCE] Add This Week in Bitcoin podcast + Fix Robosats typo

### LINKED ISSUE #932: [RESOURCE] Add This Week in Bitcoin podcast
new podcast by Chris Fisher

### PR DESCRIPTION
**Pull request by jinformatique**
small typo corrected for tag bitcoin-only

### CODE REVIEW

**Comment by BitPreto** [comment]
Hi @jinformatique thanks for your contribution! while waiting for review I will rename the PR since the robosats typo is not the only contrib you did here, thanks for your update on the podcast! Now I have a question for you, are you inside the PBN content builders telegram group linked in the readme of the repo?

**Comment by jinformatique** [comment]
Hi, yes I'm in the Telegram group you are mentioning with the user @jinformatique

**Comment by jinformatique** [comment]
Hi, I closed and deleted the other PR, to put all changes in only one PR, this one.

**Comment by BitPreto** [comment]
Your commits look good on my side, now everything is in the hands of the repo coordinator. Hear you soon :)

**Comment by Asi0Flammeus** [comment]
Everything seems good to me! 
Thanks for the content creation and the tag typo ;-)

**Pull request merged**
