### PR TITLE
Proofreading eco102 - vi

### PR DESCRIPTION
**Pull request by Henry-Da0**

### CODE REVIEW

**Comment by Henry-Da0** [comment]
Hi @MariJJhodl could you have a look please. The hardest task ever :-D

**Comment by MariJJhodl** [comment]
@Henry-Da0 Really? Can you be more precise on your comment?

**Comment by Henry-Da0** [comment]
@MariJJhodl because this one is not a technical one, it is about philosophy so it is quite hard to make a good translation.

**Comment by MariJJhodl** [comment]
@Henry-Da0 Apart from the difficulty with the technical terms, is the initial content clearly written according to you?
Besides, are you satisfied with your final proofreading result?

**Comment by Henry-Da0** [comment]
> @Henry-Da0 Apart from the difficulty with the technical terms, is the initial content clearly written according to you? Besides, are you satisfied with your final proofreading result?

The current AI translation version is not good. So I am using Chat GPT to translate from French (original language) to Vietnamese before comparing with the current translated version + English version then do proofreading.
I am satisfied with the final work. And also would love to learn if some one can improve it.

**Comment by MariJJhodl** [comment]
Thank you for your feedback

**Pull request merged**
